title:            时间的空间
keywords :        生活, 感悟, 通信, python, 编程, zhatrix
description:      生活点滴记录
url:              http://zhatrix.com
# baseurl: /
encoding: utf-8
markdown: redcarpet
redcarpet: 
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough", "underline"]

pygments: true
permalink: /blog/:year/:month/:day/:title
date_format: "ordinal"
